version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    commit-message:
      prefix: "ci:"
    schedule:
      interval: "daily"
    labels:
      - "Type: Dependencies"
      - "Component: CI/CD"

  # Maintain dependencies for rust crates
  - package-ecosystem: "cargo"
    directory: "/"
    commit-message:
      prefix: "build:"
    schedule:
      interval: "daily"
    labels:
      - "Type: Dependencies"
      - "Implementation: Rust"

