name: CI
on: [push, pull_request]

permissions:
  contents: read #  to fetch code (actions/checkout)

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  RUST_BACKTRACE: short
  # RUSTFLAGS: "-D warnings -W unreachable-pub -W bare-trait-objects"
  RUSTUP_MAX_RETRIES: 10
  RUST_CHANNEL: stable

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build: [stable]
        include:
          - build: stable
            os: ubuntu-latest
            rust: stable
    steps:
    - uses: actions/checkout@master
    - name: Install Rust
      run: |
        rustup update ${{ matrix.rust }} --no-self-update
        rustup default ${{ matrix.rust }}
    - name: Cache Dependencies
      uses: Swatinem/rust-cache@v2
      with:
        key: ${{ env.RUST_CHANNEL }}
    - run: cargo test --verbose

  rustfmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install Rust
      run: |
        rustup update stable --no-self-update
        rustup default stable
        rustup component add rustfmt
    - name: Cache Dependencies
      uses: Swatinem/rust-cache@v2
      with:
        key: ${{ env.RUST_CHANNEL }}
    - run: cargo fmt -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install Rust
      run: |
        rustup update stable --no-self-update
        rustup default stable
        rustup component add clippy
    - name: Cache Dependencies
      uses: Swatinem/rust-cache@v2
      with:
        key: ${{ env.RUST_CHANNEL }}
    - run: cargo clippy --verbose

  doc:
    name: Check Documentation
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install Rust
      run: |
        rustup update stable --no-self-update
        rustup default stable
        rustup component add rust-docs
    - name: Cache Dependencies
      uses: Swatinem/rust-cache@v2
      with:
        key: ${{ env.RUST_CHANNEL }}
    - name: Run rustdoc
      run: RUSTDOCFLAGS="-D warnings" cargo doc --verbose --all-features

